# Generated by Django 6.0.3 on 2026-05-30 14:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.UUIDField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'energy_records',
            },
        ),
        migrations.CreateModel(
            name='MemberModel',
            fields=[
                ('member_id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('fiscal_code', models.CharField(max_length=50, null=True)),
                ('street', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('postal_code', models.CharField(max_length=20, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('occurred_on', models.DateTimeField()),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'outbox_events',
            },
        ),
    ]
